# Generated by Django 3.2.23 on 2025-02-01 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opi_id', models.IntegerField(unique=True, verbose_name='OPIS Truckstop ID')),
                ('name', models.CharField(max_length=50, verbose_name='Truckstop Name')),
                ('rack_id', models.IntegerField(verbose_name='Rack ID')),
                ('gas_price', models.DecimalField(decimal_places=9, max_digits=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fueler.city')),
            ],
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('name', 'state'), name='unique_city_state'),
        ),
    ]
