# Generated by Django 3.2.23 on 2025-02-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fueler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelstation',
            old_name='opi_id',
            new_name='opis_id',
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='address',
            field=models.CharField(default='NOT SET', max_length=50, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
