# Generated by Django 3.2.23 on 2025-02-01 10:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fueler", "0002_auto_20250201_1017"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelstation",
            name="latitude",
            field=models.DecimalField(
                decimal_places=5, default=Decimal("0"), max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="fuelstation",
            name="longitude",
            field=models.DecimalField(
                decimal_places=5, default=Decimal("0"), max_digits=8
            ),
        ),
    ]
